/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description 校验账密，下发 access token（HttpOnly Cookie）与 refresh token / sign_secret
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录凭据 */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_LoginResponse"];
                    };
                };
                /** @description 1001 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1005 登录限流（5 次/分钟/IP） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 携带 refresh_token 时服务端吊销；始终清除 access Cookie
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description refresh token（可选，携带则吊销） */
            requestBody?: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-any"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 轮换 refresh token：旧 token 作废并返回新 token + 新 access token + sign_secret
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 旧 refresh token */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.RefreshRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_RefreshResponse"];
                    };
                };
                /** @description 1001 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1101 refresh token 无效或已轮换 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1005 刷新限流 */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 仪表盘聚合
         * @description 账户汇总（基准 10000 + 累计已平仓 PnL）、活跃交易员、最近 5 条持仓、AI/交易所延迟
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_DashboardSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 模型列表
         * @description 分页? 否——返回全部未删除模型，支持 fields 白名单过滤
         */
        get: {
            parameters: {
                query?: {
                    /** @description 逗号分隔的字段白名单，如 id,name */
                    fields?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_AIModelDTOList"];
                    };
                };
                /** @description 1002 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建模型
         * @description API Key 仅以 RSA-OAEP(SHA-256) 密文落库；需要 X-Signature/X-Timestamp/X-Nonce 签名头
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 模型配置 */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.CreateModelRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_AIModelDTO"];
                    };
                };
                /** @description 1001 参数错误 / 签名缺失或重放 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1002 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 提供商列表
         * @description 支持的 AI 提供商（deepseek/qwen/gpt/claude/gemini/custom）
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_ProviderOptionList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新模型
         * @description Key 轮换：传新 api_key 时用当前公钥重新加密；custom 需要 base_url
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模型 ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 模型配置 */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.CreateModelRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_AIModelDTO"];
                    };
                };
                /** @description 1001 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1004 模型不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * 删除模型
         * @description 软删除
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模型 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-any"];
                    };
                };
                /** @description 1004 模型不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 模型连通测试
         * @description 请求体可选（key 省略时用已存 Key）；成功返回延迟，失败返回 1301/1302
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 模型 ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 临时 api_key（可选） */
            requestBody?: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.TestModelRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TestResult"];
                    };
                };
                /** @description 1004 模型不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1301 AI 服务失败 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1302 AI 服务超时 */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 持仓列表
         * @description 当前未平仓持仓，支持 symbol 与 fields 过滤
         */
        get: {
            parameters: {
                query?: {
                    /** @description 按交易对过滤，如 BTC-USDT */
                    symbol?: string;
                    /** @description 逗号分隔字段白名单 */
                    fields?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_PositionDTOList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/positions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 平仓
         * @description pnl 通过 JSON body 传入（{"pnl":123.45}）；body 为空视为 0。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 持仓 ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 平仓盈亏（可选） */
            requestBody?: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.ClosePositionRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_PositionDTO"];
                    };
                };
                /** @description 1001 参数错误 / 已平仓 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1004 持仓不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 交易员列表
         * @description 分页查询交易员，支持 status 过滤与 fields 白名单
         */
        get: {
            parameters: {
                query?: {
                    /** @description 页码（1 起，默认 1，上限 100000） */
                    page?: number;
                    /** @description 每页数量（默认 20，上限 100） */
                    size?: number;
                    /** @description 按状态过滤（idle/running/paused/stopped/error） */
                    status?: string;
                    /** @description 逗号分隔字段白名单 */
                    fields?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderPage"];
                    };
                };
                /** @description 1001 参数错误 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1002 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 创建交易员
         * @description 引用已存在的模型；初始状态 idle
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 交易员配置 */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.CreateTraderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1001 参数错误 / 引用模型不存在 / 签名缺失 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1002 未认证 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 交易员详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1004 交易员不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * 更新交易员
         * @description 指针字段语义：缺省不修改，显式 null 清空；running 时拒绝
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            /** @description 部分字段 */
            requestBody: {
                content: {
                    "application/json": Record<string, never> | components["schemas"]["fxcore_internal_api_v1_dto.UpdateTraderRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1001 参数错误 / running 中不可修改 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1004 交易员不存在 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/traders/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 暂停交易员 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1001 已处于 paused */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1004 交易员不存在 / 非法迁移 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traders/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 恢复交易员 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1004 交易员不存在 / 非法迁移 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1204 已在运行 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traders/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 启动交易员 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1004 交易员不存在 / 非法迁移 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1204 已在运行 */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/traders/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 停止交易员 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 交易员 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO"];
                    };
                };
                /** @description 1001 已处于 stopped */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
                /** @description 1004 交易员不存在 / 非法迁移 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * WebSocket 实时推送
         * @description 鉴权：query token 为 JWT access token；5s 推一次仪表盘快照，30s 心跳
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebSocket 升级成功 */
                101: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": string;
                    };
                };
                /** @description 1002 token 无效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["fxcore_internal_api_v1_dto.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.AIModelDTO": {
            /** @description 脱敏，如 sk-****abcd */
            api_key_prefix?: string;
            config?: number[];
            created_at?: string;
            id?: string;
            last_test_at?: string;
            model_name?: string;
            name?: string;
            provider?: string;
            rotated_at?: string;
            /** @description active | inactive | error */
            status?: string;
        };
        "fxcore_internal_api_v1_dto.AccountSummary": {
            daily_pnl?: number;
            total_balance?: number;
            total_pnl?: number;
        };
        "fxcore_internal_api_v1_dto.ActiveHours": {
            /** @description "HH:MM" */
            end?: string;
            /** @description "HH:MM" */
            start?: string;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-any": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            /** @description 业务数据 */
            data?: unknown;
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_AIModelDTO": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.AIModelDTO"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_AIModelDTOList": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            /** @description 业务数据 */
            data?: components["schemas"]["fxcore_internal_api_v1_dto.AIModelDTO"][];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_DashboardSummary": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.DashboardSummary"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_LoginResponse": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.LoginResponse"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_PositionDTO": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.PositionDTO"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_PositionDTOList": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            /** @description 业务数据 */
            data?: components["schemas"]["fxcore_internal_api_v1_dto.PositionDTO"][];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_ProviderOptionList": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            /** @description 业务数据 */
            data?: components["schemas"]["fxcore_internal_api_v1_dto.ProviderOption"][];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_RefreshResponse": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.RefreshResponse"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TestResult": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.TestResult"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderDTO": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.TraderDTO"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ApiResponse-fxcore_internal_api_v1_dto_TraderPage": {
            /** @description 业务码，见 internal/middleware/error.go 矩阵 */
            code?: number;
            data?: components["schemas"]["fxcore_internal_api_v1_dto.TraderPage"];
            /** @description 人类可读消息 */
            message?: string;
            request_id?: string;
            /** @description unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.ClosePositionRequest": {
            pnl?: number;
        };
        "fxcore_internal_api_v1_dto.CreateModelRequest": {
            api_key: string;
            /** @description 温度、TopP 等 */
            config?: number[];
            model_name: string;
            name: string;
            provider: string;
        };
        "fxcore_internal_api_v1_dto.CreateTraderRequest": {
            exchange: string;
            model_config: components["schemas"]["fxcore_internal_api_v1_dto.ModelConfig"];
            name: string;
            risk_config: components["schemas"]["fxcore_internal_api_v1_dto.RiskConfig"];
            schedule?: components["schemas"]["fxcore_internal_api_v1_dto.Schedule"];
            strategy_id: string;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.DashboardSummary": {
            account?: components["schemas"]["fxcore_internal_api_v1_dto.AccountSummary"];
            /** @description 运行中的前 5 个 */
            active_traders?: components["schemas"]["fxcore_internal_api_v1_dto.TraderDTO"][];
            /** @description 最新 5 条 */
            recent_positions?: components["schemas"]["fxcore_internal_api_v1_dto.PositionDTO"][];
            system_health?: components["schemas"]["fxcore_internal_api_v1_dto.SystemHealth"];
        };
        "fxcore_internal_api_v1_dto.ErrorResponse": {
            /** @description 业务错误码（1001-1500 矩阵） */
            code?: number;
            /** @description 1001 时字段级错误映射，其余为 null */
            data?: {
                [key: string]: unknown;
            };
            /** @description 可读错误信息 */
            message?: string;
            /** @description 链路追踪 ID */
            request_id?: string;
            /** @description Unix 毫秒 */
            timestamp?: number;
        };
        "fxcore_internal_api_v1_dto.LoginRequest": {
            email: string;
            password: string;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.LoginResponse": {
            access_token?: string;
            refresh_token?: string;
            sign_secret?: string;
            user?: components["schemas"]["fxcore_internal_api_v1_dto.UserDTO"];
        };
        "fxcore_internal_api_v1_dto.MetricsDTO": {
            daily_pnl?: number;
            total_pnl?: number;
            trade_count?: number;
            /** @description 0~1 */
            win_rate?: number;
        };
        "fxcore_internal_api_v1_dto.ModelConfig": {
            /** @description 引用 internal/model 中的 AI 模型 ID */
            model_id: string;
            parameters?: number[];
            provider: string;
        };
        "fxcore_internal_api_v1_dto.Paginator": {
            page?: number;
            page_size?: number;
            total?: number;
            total_pages?: number;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.PositionDTO": {
            closed_at?: string;
            entry_price?: number;
            id?: string;
            opened_at?: string;
            pnl?: number;
            /** @description long | short */
            side?: string;
            size?: number;
            symbol?: string;
            trader_id?: string;
        };
        "fxcore_internal_api_v1_dto.ProviderOption": {
            models?: string[];
            provider?: string;
        };
        "fxcore_internal_api_v1_dto.RefreshRequest": {
            refresh_token: string;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.RefreshResponse": {
            access_token?: string;
            refresh_token?: string;
            sign_secret?: string;
        };
        "fxcore_internal_api_v1_dto.RiskConfig": {
            max_daily_loss?: number;
            max_position_size: number;
            stop_loss?: number;
            take_profit?: number;
        };
        "fxcore_internal_api_v1_dto.Schedule": {
            active_hours?: components["schemas"]["fxcore_internal_api_v1_dto.ActiveHours"][];
            /** @description 轮询间隔（秒） */
            interval?: number;
        };
        "fxcore_internal_api_v1_dto.SystemHealth": {
            /** @description 毫秒，-1 表示不可用 */
            ai_latency?: number;
            /** @description 毫秒，-1 表示不可用 */
            exchange_latency?: number;
            /** @description healthy | degraded */
            status?: string;
        };
        "fxcore_internal_api_v1_dto.TestModelRequest": {
            api_key?: string;
            model_name?: string;
            provider?: string;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.TestResult": {
            error?: string;
            /** @description 毫秒 */
            latency?: number;
            success?: boolean;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.TraderDTO": {
            created_at?: string;
            exchange?: string;
            id?: string;
            metrics?: components["schemas"]["fxcore_internal_api_v1_dto.MetricsDTO"];
            model_config?: components["schemas"]["fxcore_internal_api_v1_dto.ModelConfig"];
            name?: string;
            risk_config?: components["schemas"]["fxcore_internal_api_v1_dto.RiskConfig"];
            schedule?: components["schemas"]["fxcore_internal_api_v1_dto.Schedule"];
            /** @description idle | running | paused | stopped | error */
            status?: string;
            strategy_id?: string;
            updated_at?: string;
        };
        /** @description 业务数据 */
        "fxcore_internal_api_v1_dto.TraderPage": {
            items?: components["schemas"]["fxcore_internal_api_v1_dto.TraderDTO"][];
            pagination?: components["schemas"]["fxcore_internal_api_v1_dto.Paginator"];
        };
        "fxcore_internal_api_v1_dto.UpdateTraderRequest": {
            exchange?: string;
            model_config?: components["schemas"]["fxcore_internal_api_v1_dto.ModelConfig"];
            name?: string;
            risk_config?: components["schemas"]["fxcore_internal_api_v1_dto.RiskConfig"];
            schedule?: components["schemas"]["fxcore_internal_api_v1_dto.Schedule"];
            strategy_id?: string;
        };
        "fxcore_internal_api_v1_dto.UserDTO": {
            avatar?: string;
            email?: string;
            id?: string;
            nickname?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
